name: Trigger auto deployment for queuereader

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'queuereaderapp/**'
    - '.github/workflows/queuereader-AutoDeployTrigger-a64c22ac-bfb1-4c6f-b092-f3ff7cdaeadb.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: conhack.azurecr.io

          username: ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }}
          password: ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: conhack.azurecr.io/queuereader:${{ github.sha }}
          file: ./queuereaderapp/Dockerfile
          context: ./queuereaderapp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.QUEUEREADER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt --verbose
            az containerapp registry set -n queuereader -g conapps-rg --server conhack.azurecr.io --username  ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }} --password ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }} --verbose
            #az containerapp update -n queuereader -g conapps-rg --image conhack.azurecr.io/queuereader:${{ github.sha }} --verbose
